/**
 * @file PowerPlant.h
 * @brief Defines the PowerPlant class for managing power generation in the simulation.
 */

#ifndef POWERPLANT_H
#define POWERPLANT_H

#include "ProductionUtility.h"
#include "Energy.h"

/**
 * @class PowerPlant
 * @brief Represents a power plant that generates electricity.
 */
class PowerPlant : public ProductionUtility
{
private:
    Resources *energy; ///< Pointer to the Energy resource

public:
    /**
     * @brief Constructs a PowerPlant with specified parameters.
     * @param name Name of the power plant
     * @param department Pointer to the Resource Department
     * @param resource Pointer to the Energy resource
     * @param numworkers Number of workers for the power plant
     */
    PowerPlant(std::string name, ResourceDepartment *department, Energy *resource, int numworkers);

    /**
     * @brief Default destructor for PowerPlant.
     */
    ~PowerPlant();

    /**
     * @brief Starts the power production process.
     */
    void startProduction() override; // Starts power production

    /**
     * @brief Gets the product generated by the power plant.
     * @return The name of the product
     */
    std::string getProduct() const override;
};

#endif // POWERPLANT_H
