/**
 * @file WaterSupply.h
 * @brief Defines the WaterSupply class for managing water production in the simulation.
 */

#ifndef WATERSUPPLY_H
#define WATERSUPPLY_H

#include "ProductionUtility.h"
#include "Water.h"

/**
 * @class WaterSupply
 * @brief Represents a water supply utility that generates and manages water resources.
 */
class WaterSupply : public ProductionUtility
{
private:
    Resources *water; ///< Pointer to the Water resource

public:
    /**
     * @brief Constructs a WaterSupply with specified parameters.
     * @param name Name of the water supply
     * @param department Pointer to the Resource Department
     * @param resource Pointer to the Water resource
     * @param numworkers Number of workers for the water supply
     */
    WaterSupply(std::string name, ResourceDepartment *department, Water *resource, int numworkers,WiseBucks* app);

    /**
     * @brief Default destructor for WaterSupply.
     */
    ~WaterSupply();

    /**
     * @brief Starts the water production process.
     */
    void startProduction() override; // Starts water production

    /**
     * @brief Gets the product generated by the water supply.
     * @return The name of the product
     */
    std::string getProduct() const override;
};

#endif // WATERSUPPLY_H
